from typing import Dict, List, Any, Optional
from jinja2 import Environment, FileSystemLoader, Template
from pathlib import Path
import json
import yaml
from datetime import datetime
import os

class DocumentationGenerator:
    """Generates documentation for applications and configurations."""

    def __init__(self, templates_dir: str = "templates"):
        self.templates_dir = Path(templates_dir)
        self.templates_dir.mkdir(exist_ok=True)

        # Setup Jinja2 environment
        self.env = Environment(
            loader=FileSystemLoader(str(self.templates_dir)),
            autoescape=True
        )

        # Initialize default templates
        self._create_default_templates()

    def _create_default_templates(self):
        """Create default documentation templates."""

        # Application overview template
        app_overview_template = """# {{ application.name }}

**Type:** {{ application.type | replace('_', ' ') | title }}
**Environment:** {{ application.environment | title }}
**Status:** {{ application.health_status | title }}
**Last Updated:** {{ application.last_updated.strftime('%Y-%m-%d %H:%M:%S') }}

{{ application.description or "No description available." }}

## Infrastructure

{% if application.host -%}
- **Host:** {{ application.host }}
{% endif -%}
{% if application.port -%}
- **Port:** {{ application.port }}
{% endif -%}
{% if application.container_id -%}
- **Container ID:** {{ application.container_id }}
{% endif -%}
{% if application.k8s_namespace -%}
- **Kubernetes Namespace:** {{ application.k8s_namespace }}
- **Kubernetes Deployment:** {{ application.k8s_deployment or 'N/A' }}
{% endif %}

## Configuration

{% if application.configurations -%}
### Configuration Items

| Key | Source | Secret | Description |
|-----|--------|---------|-------------|
{% for config in application.configurations -%}
| `{{ config.key }}` | {{ config.source }} | {{ '🔒' if config.is_secret else '🔓' }} | {{ config.description or 'No description' }} |
{% endfor %}

### Environment Variables

{% if application.environment_variables -%}
{% for key, value in application.environment_variables.items() -%}
- `{{ key }}`: {{ value if not ('secret' in key.lower() or 'password' in key.lower() or 'key' in key.lower()) else '***HIDDEN***' }}
{% endfor %}
{% else -%}
No environment variables configured.
{% endif %}
{% else -%}
No configuration items found.
{% endif %}

## Integrations

{% if application.integrations -%}
{% for integration in application.integrations -%}
### {{ integration.name }}

- **Type:** {{ integration.type | replace('_', ' ') | title }}
- **Target:** {{ integration.target_app }}
- **Status:** {{ integration.health_status or 'Unknown' }}
{% if integration.health_check_url -%}
- **Health Check:** {{ integration.health_check_url }}
{% endif %}

{% endfor %}
{% else -%}
No integrations configured.
{% endif %}

## Compliance

{% if application.compliance_score -%}
**Compliance Score:** {{ "%.1f" | format(application.compliance_score) }}/100

{% if application.compliance_issues -%}
### Open Issues

{% for issue in application.compliance_issues -%}
{% if issue.status == 'open' -%}
- **{{ issue.rule.name if issue.rule else 'Unknown Rule' }}:** {{ issue.description }}
  - *Recommendation:* {{ issue.recommendation }}
{% endif %}
{% endfor %}
{% endif %}
{% else -%}
Compliance not yet evaluated.
{% endif %}

## Links

{% if application.repository_url -%}
- [Source Code]({{ application.repository_url }})
{% endif -%}
{% if application.documentation_url -%}
- [Documentation]({{ application.documentation_url }})
{% endif -%}
{% if application.maintainer -%}
- **Maintainer:** {{ application.maintainer }}
{% endif %}

---
*Generated by ConfigMaster on {{ generation_time.strftime('%Y-%m-%d %H:%M:%S') }}*
"""

        # Configuration reference template
        config_reference_template = """# Configuration Reference

## Applications by Type

{% for app_type, apps in applications_by_type.items() -%}
### {{ app_type | replace('_', ' ') | title }}

{% for app in apps -%}
- [{{ app.name }}](./{{ app.id }}.md) - {{ app.environment | title }}
{% endfor %}

{% endfor %}

## Configuration Standards

### Required Configuration by Application Type

{% for app_type, standards in config_standards.items() -%}
#### {{ app_type | replace('_', ' ') | title }}

{% for standard in standards -%}
- **{{ standard.key }}**: {{ standard.description }}
  - Type: {{ standard.type }}
  - Required: {{ 'Yes' if standard.required else 'No' }}
  - Default: `{{ standard.default if standard.default else 'None' }}`
{% endfor %}

{% endfor %}

## Integration Patterns

{% for pattern in integration_patterns -%}
### {{ pattern.name }}

{{ pattern.description }}

**Use Cases:**
{% for use_case in pattern.use_cases -%}
- {{ use_case }}
{% endfor %}

**Configuration:**
```yaml
{{ pattern.config_example | tojson(indent=2) }}
```

{% endfor %}

---
*Generated by ConfigMaster on {{ generation_time.strftime('%Y-%m-%d %H:%M:%S') }}*
"""

        # Architecture overview template
        architecture_template = """# Architecture Overview

## System Architecture

```mermaid
graph TB
    subgraph "{{ environment | title }} Environment"
{% for app in applications -%}
        {{ app.id | replace('-', '_') }}["{{ app.name }}<br/>{{ app.type | replace('_', ' ') | title }}"]
{% endfor %}
    end

{% for integration in integrations -%}
    {{ integration.source_id | replace('-', '_') }} --> {{ integration.target_id | replace('-', '_') }}
{% endfor %}
```

## Applications Summary

| Application | Type | Status | Compliance Score |
|-------------|------|--------|------------------|
{% for app in applications -%}
| [{{ app.name }}](./{{ app.id }}.md) | {{ app.type | replace('_', ' ') | title }} | {{ app.health_status | title }} | {{ "%.1f" | format(app.compliance_score) if app.compliance_score else 'N/A' }}/100 |
{% endfor %}

## Infrastructure Distribution

### By Environment
{% for env, count in environment_stats.items() -%}
- **{{ env | title }}**: {{ count }} applications
{% endfor %}

### By Type
{% for type, count in type_stats.items() -%}
- **{{ type | replace('_', ' ') | title }}**: {{ count }} applications
{% endfor %}

## Integration Map

{% for integration in integrations -%}
### {{ integration.name }}

- **Source:** {{ integration.source_app }}
- **Target:** {{ integration.target_app }}
- **Type:** {{ integration.type | replace('_', ' ') | title }}
- **Status:** {{ integration.health_status or 'Unknown' }}

{% endfor %}

---
*Generated by ConfigMaster on {{ generation_time.strftime('%Y-%m-%d %H:%M:%S') }}*
"""

        # Write templates to files
        templates = {
            'application.md': app_overview_template,
            'config_reference.md': config_reference_template,
            'architecture.md': architecture_template
        }

        for template_name, template_content in templates.items():
            template_path = self.templates_dir / template_name
            with open(template_path, 'w') as f:
                f.write(template_content)

    def generate_application_docs(self, application: Dict[str, Any], output_dir: str = "docs") -> str:
        """Generate documentation for a single application."""
        output_path = Path(output_dir)
        output_path.mkdir(exist_ok=True)

        template = self.env.get_template('application.md')

        content = template.render(
            application=application,
            generation_time=datetime.now()
        )

        doc_file = output_path / f"{application['id']}.md"
        with open(doc_file, 'w') as f:
            f.write(content)

        return str(doc_file)

    def generate_config_reference(self, applications: List[Dict[str, Any]], output_dir: str = "docs") -> str:
        """Generate configuration reference documentation."""
        output_path = Path(output_dir)
        output_path.mkdir(exist_ok=True)

        # Group applications by type
        applications_by_type = {}
        for app in applications:
            app_type = app['type']
            if app_type not in applications_by_type:
                applications_by_type[app_type] = []
            applications_by_type[app_type].append(app)

        # Generate configuration standards
        config_standards = self._generate_config_standards()

        # Generate integration patterns
        integration_patterns = self._generate_integration_patterns()

        template = self.env.get_template('config_reference.md')

        content = template.render(
            applications_by_type=applications_by_type,
            config_standards=config_standards,
            integration_patterns=integration_patterns,
            generation_time=datetime.now()
        )

        doc_file = output_path / "config_reference.md"
        with open(doc_file, 'w') as f:
            f.write(content)

        return str(doc_file)

    def generate_architecture_docs(self, applications: List[Dict[str, Any]], environment: str = "all", output_dir: str = "docs") -> str:
        """Generate architecture documentation."""
        output_path = Path(output_dir)
        output_path.mkdir(exist_ok=True)

        # Filter applications by environment if specified
        if environment != "all":
            applications = [app for app in applications if app['environment'] == environment]

        # Generate statistics
        environment_stats = {}
        type_stats = {}
        for app in applications:
            env = app['environment']
            app_type = app['type']
            environment_stats[env] = environment_stats.get(env, 0) + 1
            type_stats[app_type] = type_stats.get(app_type, 0) + 1

        # Extract integrations
        integrations = []
        for app in applications:
            for integration in app.get('integrations', []):
                integrations.append({
                    'name': integration['name'],
                    'source_app': app['name'],
                    'source_id': app['id'],
                    'target_app': integration['target_app'],
                    'target_id': integration.get('target_id', integration['target_app'].replace(' ', '-').lower()),
                    'type': integration['type'],
                    'health_status': integration.get('health_status')
                })

        template = self.env.get_template('architecture.md')

        content = template.render(
            applications=applications,
            environment=environment,
            environment_stats=environment_stats,
            type_stats=type_stats,
            integrations=integrations,
            generation_time=datetime.now()
        )

        doc_file = output_path / f"architecture_{environment}.md"
        with open(doc_file, 'w') as f:
            f.write(content)

        return str(doc_file)

    def generate_yaml_config(self, application: Dict[str, Any], output_dir: str = "configs") -> str:
        """Generate YAML configuration file for an application."""
        output_path = Path(output_dir)
        output_path.mkdir(exist_ok=True)

        # Create configuration structure
        config_data = {
            'application': {
                'name': application['name'],
                'type': application['type'],
                'environment': application['environment'],
                'version': application.get('version', '1.0.0')
            },
            'infrastructure': {
                'host': application.get('host'),
                'port': application.get('port'),
                'path': application.get('path')
            },
            'configuration': {},
            'integrations': []
        }

        # Add configurations (excluding secrets)
        for config in application.get('configurations', []):
            if not config.get('is_secret', False):
                config_data['configuration'][config['key']] = {
                    'value': config['value'],
                    'source': config['source'],
                    'description': config.get('description')
                }

        # Add integrations
        for integration in application.get('integrations', []):
            config_data['integrations'].append({
                'name': integration['name'],
                'type': integration['type'],
                'target': integration['target_app'],
                'configuration': integration.get('configuration', {}),
                'health_check': integration.get('health_check_url')
            })

        # Remove None values
        config_data = self._remove_none_values(config_data)

        config_file = output_path / f"{application['id']}.yaml"
        with open(config_file, 'w') as f:
            yaml.dump(config_data, f, default_flow_style=False, indent=2)

        return str(config_file)

    def generate_terraform_config(self, applications: List[Dict[str, Any]], output_dir: str = "terraform") -> str:
        """Generate Terraform configuration for infrastructure as code."""
        output_path = Path(output_dir)
        output_path.mkdir(exist_ok=True)

        terraform_config = []

        # Add provider configuration
        terraform_config.append('''terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.20"
    }
  }
}

provider "docker" {}

provider "kubernetes" {
  config_path = "~/.kube/config"
}''')

        for app in applications:
            if app.get('container_id'):
                # Generate Docker configuration
                terraform_config.append(f'''
# Docker configuration for {app['name']}
resource "docker_image" "{app['id'].replace('-', '_')}" {{
  name = "{app['name']}:latest"
}}

resource "docker_container" "{app['id'].replace('-', '_')}" {{
  image = docker_image.{app['id'].replace('-', '_')}.name
  name  = "{app['name']}"

  ports {{
    internal = {app.get('port', 8000)}
    external = {app.get('port', 8000)}
  }}

  env = [
{self._generate_env_vars(app.get('environment_variables', {}))}
  ]
}}''')

            elif app.get('k8s_namespace'):
                # Generate Kubernetes configuration
                terraform_config.append(f'''
# Kubernetes configuration for {app['name']}
resource "kubernetes_deployment" "{app['id'].replace('-', '_')}" {{
  metadata {{
    name      = "{app['name']}"
    namespace = "{app['k8s_namespace']}"
    labels = {{
      app = "{app['name']}"
    }}
  }}

  spec {{
    replicas = 1

    selector {{
      match_labels = {{
        app = "{app['name']}"
      }}
    }}

    template {{
      metadata {{
        labels = {{
          app = "{app['name']}"
        }}
      }}

      spec {{
        container {{
          image = "{app['name']}:latest"
          name  = "{app['name']}"

          port {{
            container_port = {app.get('port', 8000)}
          }}

          env {{
{self._generate_k8s_env_vars(app.get('environment_variables', {}))}
          }}
        }}
      }}
    }}
  }}
}}

resource "kubernetes_service" "{app['id'].replace('-', '_')}" {{
  metadata {{
    name      = "{app['name']}-service"
    namespace = "{app['k8s_namespace']}"
  }}
  spec {{
    selector = {{
      app = "{app['name']}"
    }}
    port {{
      port        = {app.get('port', 8000)}
      target_port = {app.get('port', 8000)}
    }}
    type = "ClusterIP"
  }}
}}''')

        terraform_file = output_path / "main.tf"
        with open(terraform_file, 'w') as f:
            f.write('\n'.join(terraform_config))

        return str(terraform_file)

    def _generate_config_standards(self) -> Dict[str, List[Dict[str, Any]]]:
        """Generate configuration standards for different application types."""
        return {
            'web_application': [
                {'key': 'PORT', 'description': 'Application port', 'type': 'integer', 'required': True, 'default': '3000'},
                {'key': 'HOST', 'description': 'Host address', 'type': 'string', 'required': False, 'default': '0.0.0.0'},
                {'key': 'NODE_ENV', 'description': 'Environment mode', 'type': 'string', 'required': True, 'default': 'production'}
            ],
            'api_service': [
                {'key': 'DATABASE_URL', 'description': 'Database connection string', 'type': 'string', 'required': True, 'default': None},
                {'key': 'API_KEY', 'description': 'API authentication key', 'type': 'string', 'required': True, 'default': None},
                {'key': 'LOG_LEVEL', 'description': 'Logging level', 'type': 'string', 'required': False, 'default': 'info'}
            ],
            'database': [
                {'key': 'DB_PASSWORD', 'description': 'Database password', 'type': 'string', 'required': True, 'default': None},
                {'key': 'DB_NAME', 'description': 'Database name', 'type': 'string', 'required': True, 'default': None},
                {'key': 'BACKUP_ENABLED', 'description': 'Enable backups', 'type': 'boolean', 'required': False, 'default': 'true'}
            ]
        }

    def _generate_integration_patterns(self) -> List[Dict[str, Any]]:
        """Generate common integration patterns."""
        return [
            {
                'name': 'API to Database',
                'description': 'Standard pattern for API services connecting to databases',
                'use_cases': ['CRUD operations', 'Data persistence', 'Query processing'],
                'config_example': {
                    'type': 'database',
                    'connection': {
                        'host': '${DATABASE_HOST}',
                        'port': '${DATABASE_PORT}',
                        'database': '${DATABASE_NAME}',
                        'username': '${DATABASE_USER}',
                        'password': '${DATABASE_PASSWORD}'
                    },
                    'pool': {
                        'min_connections': 5,
                        'max_connections': 20
                    }
                }
            },
            {
                'name': 'Service to Service API',
                'description': 'REST API communication between microservices',
                'use_cases': ['Microservice communication', 'Data exchange', 'Service orchestration'],
                'config_example': {
                    'type': 'api',
                    'endpoint': '${TARGET_SERVICE_URL}',
                    'authentication': {
                        'type': 'bearer_token',
                        'token': '${API_TOKEN}'
                    },
                    'timeout': 30,
                    'retry_attempts': 3
                }
            }
        ]

    def _generate_env_vars(self, env_vars: Dict[str, str]) -> str:
        """Generate environment variable list for Terraform Docker."""
        return ',\n'.join([f'    "{key}={value}"' for key, value in env_vars.items()])

    def _generate_k8s_env_vars(self, env_vars: Dict[str, str]) -> str:
        """Generate environment variable configuration for Kubernetes."""
        return '\n'.join([f'            name  = "{key}"\n            value = "{value}"' for key, value in env_vars.items()])

    def _remove_none_values(self, data: Any) -> Any:
        """Recursively remove None values from data structure."""
        if isinstance(data, dict):
            return {k: self._remove_none_values(v) for k, v in data.items() if v is not None}
        elif isinstance(data, list):
            return [self._remove_none_values(item) for item in data if item is not None]
        else:
            return data